#!/usr/bin/env bash
# One command per checkout: install the pinned Haxe compiler, wire Serena's Haxe language server and
# provide ast-grep with a Haxe grammar.
#
#   tools/setup.sh      # needs curl, sha256sum, tar, flock, git, node + npm, cc
#
# Compiler: the build of GeTechG/haxe named in tools/haxe-build.pin (`<build key> <sha256 of the archive>`),
# downloaded from that repository's `builds` release, verified, and installed once per user in
# ${XDG_CACHE_HOME:-~/.cache}/haxe-build/<key>; the gitignored `.haxe` symlink points at it.
# Changing the compiler = changing the pin file.
#
# Language server: the published vshaxe only speaks `--wait stdio`, which Haxe 5 dropped, so
# vshaxe/haxe-language-server is built from source at $LS_COMMIT (it talks to the compiler over a socket)
# into ${XDG_CACHE_HOME:-~/.cache}/haxe-language-server/<commit>.
#
# Structural search: ast-grep knows no Haxe, so the ast-grep $SG_VERSION binary (the npm registry archive of
# @ast-grep/cli-linux-x64-gnu, verified against $SG_SHA256; nothing of it is run to install it) goes into
# ${XDG_CACHE_HOME:-~/.cache}/ast-grep/<version>-<sha256> and the grammar GeTechG/tree-sitter-haxe is built at
# $GRAMMAR_COMMIT into ${XDG_CACHE_HOME:-~/.cache}/tree-sitter-haxe/<commit> (the repository commits its
# generated src/parser.c, so the system C compiler is the whole build). The gitignored `.ast-grep/` holds
# links to both; sgconfig.yml names the library.
#
# Re-run after adding or removing source files (the display config lists every module); restart Serena after.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}"
LS_COMMIT=e865ce6ffa9299960d558728948691b7a5e9d4a2
SG_VERSION=0.45.3
SG_SHA256=53828b0acd21dde9f866be2c8513135bf90db9f0c2d931475b8029c534be4ce9
GRAMMAR_COMMIT=31ae7eb010e18975fd73cd65e14c71ef5054f9c7
MARK="# GENERATED by tools/setup.sh"

# --- compiler ---------------------------------------------------------------------------------------------
read -r KEY WANT < "$ROOT/tools/haxe-build.pin"
[[ $KEY =~ ^[0-9a-f]{40}$ && $WANT =~ ^[0-9a-f]{64}$ ]] || {
  echo "setup: tools/haxe-build.pin must be one line: <build key, 40 hex> <sha256, 64 hex>" >&2; exit 1; }
HAXE_DIR="$CACHE/haxe-build/$KEY"
mkdir -p "$CACHE/haxe-build"
# One installer per build key at a time: a second checkout waits here, then finds the finished install.
exec 9> "$HAXE_DIR.lock"
flock 9
if [ ! -x "$HAXE_DIR/haxe" ]; then
  ASSET="haxe-linux64-$KEY.tar.gz"
  TMP="$(mktemp -d "$HAXE_DIR.install.XXXXXX")"
  trap 'rm -rf "$TMP" "$TMP.tar.gz"' EXIT
  echo "setup: downloading $ASSET ..."
  curl -fsSL --retry 3 -o "$TMP.tar.gz" "https://github.com/GeTechG/haxe/releases/download/builds/$ASSET"
  GOT="$(sha256sum "$TMP.tar.gz" | cut -d' ' -f1)"
  [ "$GOT" = "$WANT" ] || {
    echo "setup: refusing $ASSET: sha256 $GOT, tools/haxe-build.pin says $WANT" >&2; exit 1; }
  tar -xzf "$TMP.tar.gz" -C "$TMP"
  [ -x "$TMP/haxe" ] && [ -d "$TMP/std" ] || { echo "setup: $ASSET holds no haxe + std/" >&2; exit 1; }
  echo "$WANT" > "$TMP/.sha256"
  chmod 755 "$TMP"
  mv -T "$TMP" "$HAXE_DIR"
  rm -f "$TMP.tar.gz"
fi
# The install records the checksum it was verified against: a pin whose checksum changed under the same key
# must not silently keep the old build.
[ "$(cat "$HAXE_DIR/.sha256" 2> /dev/null)" = "$WANT" ] || {
  echo "setup: $HAXE_DIR was not installed from the archive tools/haxe-build.pin names; remove it and re-run" >&2
  exit 1; }
flock -u 9
# -T: a real `.haxe` directory is an error, not a place to drop the link into.
ln -sfnT "$HAXE_DIR" "$ROOT/.haxe"
echo "setup: $("$ROOT/.haxe/haxe" --version) -> .haxe"

# --- language server --------------------------------------------------------------------------------------
LOCAL="$ROOT/.serena/project.local.yml"
if [ -f "$LOCAL" ] && grep -qv '^\s*\(#\|$\)' "$LOCAL" && ! grep -qF "$MARK" "$LOCAL"; then
  echo "setup: $LOCAL holds your own overrides; move them aside and re-run" >&2
  exit 1
fi

LS_DIR="$CACHE/haxe-language-server/$LS_COMMIT"
if [ ! -f "$LS_DIR/bin/server.js" ]; then
  mkdir -p "$CACHE/haxe-language-server"
  TMP="$LS_DIR.tmp.$$"
  trap 'rm -rf "$TMP"' EXIT
  echo "setup: building haxe-language-server $LS_COMMIT ..."
  git init -q "$TMP"
  git -C "$TMP" fetch -q --depth 1 https://github.com/vshaxe/haxe-language-server "$LS_COMMIT"
  git -C "$TMP" checkout -q FETCH_HEAD
  (cd "$TMP" && npm ci --silent && npx lix run vshaxe-build -t language-server > /dev/null)
  test -f "$TMP/bin/server.js"
  mv -T "$TMP" "$LS_DIR" 2> /dev/null || true # a concurrent run finished first: its build is the same commit
  rm -rf "$TMP"
fi
[ -f "$LS_DIR/bin/server.js" ] || { echo "setup: no language server at $LS_DIR/bin/server.js" >&2; exit 1; }

# --- display config ---------------------------------------------------------------------------------------
# The server sends these arguments to the compiler over a socket: only -cp/-D/-w, no -lib and no --macro.
# The core does not type without a backend, so tools/display-backend supplies a do-nothing one (the
# backend template haxeui/haxeui-blank at 017a3fe, MIT like the library). Every module
# is named (dot path, no import.hx): with none the compiler's cache build types nothing and a reference
# lookup silently returns only part of the call sites. `--macro include(...)` fails in display mode.
# Left out, because they do not type as modules of a normal build: the macro package (macro context only)
# and whatever $EXCLUDE names.
EXCLUDE='^haxe\.ui\.macros\.'
DISPLAY_HXML=.serena/display.hxml
mkdir -p "$ROOT/.serena"
{
  echo "$MARK — do not edit. Re-run it after adding or removing source files."
  echo "-cp ."
  echo "-cp tools/display-backend"
  echo "-D haxeui"
  echo "-D haxeui-core=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' "$ROOT/haxelib.json")"
  echo "--interp"
  for cp in . tools/display-backend; do
    (cd "$ROOT/$cp" && find haxe -name '*.hx' ! -name import.hx | sed -e 's/\.hx$//' -e 's|/|.|g')
  done | sort -u | grep -Ev "$EXCLUDE"
} > "$ROOT/$DISPLAY_HXML"
(cd "$ROOT" && HAXE_STD_PATH=.haxe/std .haxe/haxe "$DISPLAY_HXML" --no-output) ||
  echo "setup: WARNING: $DISPLAY_HXML does not type (errors above): reference lists will be incomplete" >&2

# Serena overwrites project.local.yml when it has to auto-generate a missing project.yml.
[ -f "$ROOT/.serena/project.yml" ] || printf 'language_servers:\n- haxe\n' > "$ROOT/.serena/project.yml"
cat > "$LOCAL" << YAML
$MARK — do not edit.
language_servers:
- haxe
ls_specific_settings:
  haxe:
    buildFile: $DISPLAY_HXML
    ls_base_cmd: ["sh", "-c", 'PATH="\$PWD/.haxe:\$PATH" HAXE_STD_PATH="\$PWD/.haxe/std" exec node "$LS_DIR/bin/server.js"']
    ls_args: []
YAML
echo "setup: Serena -> $LS_DIR/bin/server.js, $(grep -c '^haxe\.' "$ROOT/$DISPLAY_HXML") modules in $DISPLAY_HXML"

# --- structural search ------------------------------------------------------------------------------------
# The directory is named by the whole pin: another checksum under the same version is another install.
SG_DIR="$CACHE/ast-grep/$SG_VERSION-$SG_SHA256"
if [ ! -x "$SG_DIR/ast-grep" ]; then
  mkdir -p "$CACHE/ast-grep"
  TMP="$SG_DIR.tmp.$$"
  trap 'rm -rf "$TMP" "$TMP.tgz"' EXIT
  echo "setup: downloading ast-grep $SG_VERSION ..."
  curl -fsSL --retry 3 -o "$TMP.tgz" \
    "https://registry.npmjs.org/@ast-grep/cli-linux-x64-gnu/-/cli-linux-x64-gnu-$SG_VERSION.tgz"
  GOT="$(sha256sum "$TMP.tgz" | cut -d' ' -f1)"
  [ "$GOT" = "$SG_SHA256" ] || {
    echo "setup: refusing ast-grep $SG_VERSION: sha256 $GOT, tools/setup.sh says $SG_SHA256" >&2; exit 1; }
  mkdir "$TMP"
  tar -xzf "$TMP.tgz" -C "$TMP" --strip-components=1 package/ast-grep
  mv -T "$TMP" "$SG_DIR" 2> /dev/null || true # a concurrent run finished first: its install is the same archive
  rm -rf "$TMP" "$TMP.tgz"
fi
[ -x "$SG_DIR/ast-grep" ] || { echo "setup: no ast-grep in $SG_DIR" >&2; exit 1; }

GRAMMAR_DIR="$CACHE/tree-sitter-haxe/$GRAMMAR_COMMIT"
if [ ! -f "$GRAMMAR_DIR/haxe.so" ]; then
  mkdir -p "$CACHE/tree-sitter-haxe"
  TMP="$GRAMMAR_DIR.tmp.$$"
  trap 'rm -rf "$TMP"' EXIT
  echo "setup: building tree-sitter-haxe $GRAMMAR_COMMIT ..."
  git init -q "$TMP"
  git -C "$TMP" fetch -q --depth 1 https://github.com/GeTechG/tree-sitter-haxe "$GRAMMAR_COMMIT"
  git -C "$TMP" checkout -q FETCH_HEAD
  mkdir "$TMP/out"
  cc -shared -fPIC -O2 -I "$TMP/src" "$TMP"/src/*.c -o "$TMP/out/haxe.so"
  mv -T "$TMP/out" "$GRAMMAR_DIR" 2> /dev/null || true # a concurrent run finished first: its build is the same commit
  rm -rf "$TMP"
fi
[ -f "$GRAMMAR_DIR/haxe.so" ] || { echo "setup: no grammar library at $GRAMMAR_DIR/haxe.so" >&2; exit 1; }

mkdir -p "$ROOT/.ast-grep"
ln -sfn "$SG_DIR/ast-grep" "$ROOT/.ast-grep/ast-grep"
ln -sfn "$GRAMMAR_DIR/haxe.so" "$ROOT/.ast-grep/haxe.so"
# Prove the pair works before saying so: the binary runs, loads the grammar through sgconfig.yml and matches.
SG_SAYS="$("$ROOT/.ast-grep/ast-grep" --version)"
(cd "$ROOT" && echo 'class A { function f() { throw new B(1); } }' |
  .ast-grep/ast-grep run -p 'throw new $T($$$A)' -l haxe --stdin > /dev/null) || {
  echo "setup: .ast-grep/ast-grep does not match Haxe with $GRAMMAR_DIR/haxe.so" >&2; exit 1; }
echo "setup: $SG_SAYS + tree-sitter-haxe ${GRAMMAR_COMMIT:0:8} -> .ast-grep"
