#!/usr/bin/env bash
# One command per checkout: install the pinned Haxe compiler and wire Serena's Haxe language server.
#
#   tools/setup.sh      # needs curl, sha256sum, tar, flock, git, node + npm
#
# Compiler: the build of GeTechG/haxe named in tools/haxe-build.pin (`<build key> <sha256 of the archive>`),
# downloaded from that repository's `builds` release, verified, and installed once per user in
# ${XDG_CACHE_HOME:-~/.cache}/haxe-build/<key>; the gitignored `.haxe` symlink points at it.
# Changing the compiler = changing the pin file.
#
# Language server: the published vshaxe only speaks `--wait stdio`, which Haxe 5 dropped, so
# vshaxe/haxe-language-server is built from source at $LS_COMMIT (it talks to the compiler over a socket)
# into ${XDG_CACHE_HOME:-~/.cache}/haxe-language-server/<commit>.
#
# Re-run after adding or removing source files (the display config lists every module); restart Serena after.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CACHE="${XDG_CACHE_HOME:-$HOME/.cache}"
LS_COMMIT=e865ce6ffa9299960d558728948691b7a5e9d4a2
MARK="# GENERATED by tools/setup.sh"

# --- compiler ---------------------------------------------------------------------------------------------
read -r KEY WANT < "$ROOT/tools/haxe-build.pin"
[[ $KEY =~ ^[0-9a-f]{40}$ && $WANT =~ ^[0-9a-f]{64}$ ]] || {
  echo "setup: tools/haxe-build.pin must be one line: <build key, 40 hex> <sha256, 64 hex>" >&2; exit 1; }
HAXE_DIR="$CACHE/haxe-build/$KEY"
mkdir -p "$CACHE/haxe-build"
# One installer per build key at a time: a second checkout waits here, then finds the finished install.
exec 9> "$HAXE_DIR.lock"
flock 9
if [ ! -x "$HAXE_DIR/haxe" ]; then
  ASSET="haxe-linux64-$KEY.tar.gz"
  TMP="$(mktemp -d "$HAXE_DIR.install.XXXXXX")"
  trap 'rm -rf "$TMP" "$TMP.tar.gz"' EXIT
  echo "setup: downloading $ASSET ..."
  curl -fsSL --retry 3 -o "$TMP.tar.gz" "https://github.com/GeTechG/haxe/releases/download/builds/$ASSET"
  GOT="$(sha256sum "$TMP.tar.gz" | cut -d' ' -f1)"
  [ "$GOT" = "$WANT" ] || {
    echo "setup: refusing $ASSET: sha256 $GOT, tools/haxe-build.pin says $WANT" >&2; exit 1; }
  tar -xzf "$TMP.tar.gz" -C "$TMP"
  [ -x "$TMP/haxe" ] && [ -d "$TMP/std" ] || { echo "setup: $ASSET holds no haxe + std/" >&2; exit 1; }
  echo "$WANT" > "$TMP/.sha256"
  chmod 755 "$TMP"
  mv -T "$TMP" "$HAXE_DIR"
  rm -f "$TMP.tar.gz"
fi
# The install records the checksum it was verified against: a pin whose checksum changed under the same key
# must not silently keep the old build.
[ "$(cat "$HAXE_DIR/.sha256" 2> /dev/null)" = "$WANT" ] || {
  echo "setup: $HAXE_DIR was not installed from the archive tools/haxe-build.pin names; remove it and re-run" >&2
  exit 1; }
flock -u 9
# -T: a real `.haxe` directory is an error, not a place to drop the link into.
ln -sfnT "$HAXE_DIR" "$ROOT/.haxe"
echo "setup: $("$ROOT/.haxe/haxe" --version) -> .haxe"

# --- language server --------------------------------------------------------------------------------------
LOCAL="$ROOT/.serena/project.local.yml"
if [ -f "$LOCAL" ] && grep -qv '^\s*\(#\|$\)' "$LOCAL" && ! grep -qF "$MARK" "$LOCAL"; then
  echo "setup: $LOCAL holds your own overrides; move them aside and re-run" >&2
  exit 1
fi

LS_DIR="$CACHE/haxe-language-server/$LS_COMMIT"
if [ ! -f "$LS_DIR/bin/server.js" ]; then
  mkdir -p "$CACHE/haxe-language-server"
  TMP="$LS_DIR.tmp.$$"
  trap 'rm -rf "$TMP"' EXIT
  echo "setup: building haxe-language-server $LS_COMMIT ..."
  git init -q "$TMP"
  git -C "$TMP" fetch -q --depth 1 https://github.com/vshaxe/haxe-language-server "$LS_COMMIT"
  git -C "$TMP" checkout -q FETCH_HEAD
  (cd "$TMP" && npm ci --silent && npx lix run vshaxe-build -t language-server > /dev/null)
  test -f "$TMP/bin/server.js"
  mv -T "$TMP" "$LS_DIR" 2> /dev/null || true # a concurrent run finished first: its build is the same commit
fi
[ -f "$LS_DIR/bin/server.js" ] || { echo "setup: no language server at $LS_DIR/bin/server.js" >&2; exit 1; }

# --- display config ---------------------------------------------------------------------------------------
# The server sends these arguments to the compiler over a socket: only -cp/-D/-w, no -lib and no --macro.
# The core does not type without a backend, so tools/display-backend supplies a do-nothing one (the
# backend template haxeui/haxeui-blank at 017a3fe, MIT like the library). Every module
# is named (dot path, no import.hx): with none the compiler's cache build types nothing and a reference
# lookup silently returns only part of the call sites. `--macro include(...)` fails in display mode.
# Left out, because they do not type as modules of a normal build: the macro package (macro context only)
# and whatever $EXCLUDE names.
EXCLUDE='^haxe\.ui\.(macros\.|focus\.BoxFocusApplicator$)'
DISPLAY_HXML=.serena/display.hxml
mkdir -p "$ROOT/.serena"
{
  echo "$MARK — do not edit. Re-run it after adding or removing source files."
  echo "-cp ."
  echo "-cp tools/display-backend"
  echo "-D haxeui"
  echo "-D haxeui-core=$(sed -n 's/.*"version": *"\([^"]*\)".*/\1/p' "$ROOT/haxelib.json")"
  echo "--interp"
  for cp in . tools/display-backend; do
    (cd "$ROOT/$cp" && find haxe -name '*.hx' ! -name import.hx | sed -e 's/\.hx$//' -e 's|/|.|g')
  done | sort -u | grep -Ev "$EXCLUDE"
} > "$ROOT/$DISPLAY_HXML"
(cd "$ROOT" && HAXE_STD_PATH=.haxe/std .haxe/haxe "$DISPLAY_HXML" --no-output) ||
  echo "setup: WARNING: $DISPLAY_HXML does not type (errors above): reference lists will be incomplete" >&2

# Serena overwrites project.local.yml when it has to auto-generate a missing project.yml.
[ -f "$ROOT/.serena/project.yml" ] || printf 'language_servers:\n- haxe\n' > "$ROOT/.serena/project.yml"
cat > "$LOCAL" << YAML
$MARK — do not edit.
language_servers:
- haxe
ls_specific_settings:
  haxe:
    buildFile: $DISPLAY_HXML
    ls_base_cmd: ["sh", "-c", 'PATH="\$PWD/.haxe:\$PATH" HAXE_STD_PATH="\$PWD/.haxe/std" exec node "$LS_DIR/bin/server.js"']
    ls_args: []
YAML
echo "setup: Serena -> $LS_DIR/bin/server.js, $(grep -c '^haxe\.' "$ROOT/$DISPLAY_HXML") modules in $DISPLAY_HXML"
